//
//  HomeViewController.swift
//  MetaPod
//
//  Created by Anderson Moura de Oliveira on 15/01/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit
import Firebase

protocol HomeViewControllerInput {
    func displayZuppers(viewModel: HomeScene.FetchZuppers.ViewModel)
}

protocol HomeViewControllerOutput {
    func fetchZuppers(request: HomeScene.FetchZuppers.Request)
}

class HomeViewController: UIViewController, HomeViewControllerInput {

    @IBOutlet weak var collectionView: UICollectionView!
    
    var output: HomeViewControllerOutput?
    var router: HomeRouter?

    var zuppers: HomeScene.FetchZuppers.ViewModel.ZuppersModel = []

    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        HomeConfigurator.sharedInstance.configure(viewController: self)
    }

    override var preferredStatusBarStyle: UIStatusBarStyle {
        return .lightContent
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupStyle()
        registerCell()
        fetchZuppers()
    }
    
    // MARK: Requests

    private func fetchZuppers() {
        let request = HomeScene.FetchZuppers.Request()
        output?.fetchZuppers(request: request)
    }
    
    // MARK: Display logic

    func displayZuppers(viewModel: HomeScene.FetchZuppers.ViewModel) {
        switch viewModel.result {
        case .success(let zuppers):
            self.zuppers = zuppers
            DispatchQueue.main.async {
                self.collectionView.reloadData()
            }
        case .failure(let errorMessege):
            print(errorMessege)
        }
    }
}

// MARK: Aux

extension HomeViewController {
    
    private func registerCell() {
        let repositoryCellNib = UINib(nibName: OwnerCollectionViewCell.cellIdentifier, bundle: nil)
        collectionView.register(repositoryCellNib, forCellWithReuseIdentifier: OwnerCollectionViewCell.cellIdentifier)
    }

    private func setupStyle() {
        collectionView.backgroundColor = .clear
    }
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension HomeViewController: HomePresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}
