//
//  HomeConfigurator.swift
//  MetaPod
//
//  Created by Anderson Moura de Oliveira on 15/01/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension HomeInteractor: HomeViewControllerOutput, HomeRouterDataSource, HomeRouterDataDestination {
}

extension HomePresenter: HomeInteractorOutput {
}

class HomeConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = HomeConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: HomeViewController) {
        
        let presenter = HomePresenter()
        presenter.output = viewController
        
        let interactor = HomeInteractor()
        interactor.output = presenter
        
        let router = HomeRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
