//
//  HomePresenter.swift
//  MetaPod
//
//  Created by Anderson Moura de Oliveira on 15/01/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol HomePresenterInput {
    func presentOwners(response: HomeScene.FetchOwners.Response)
}

protocol HomePresenterOutput: class {
    func displayOwners(viewModel: HomeScene.FetchOwners.ViewModel)
}

class HomePresenter: HomePresenterInput {
    
    weak var output: HomePresenterOutput?
    
    // MARK: Presentation logic

    func presentOwners(response: HomeScene.FetchOwners.Response) {
        let viewModel: HomeScene.FetchOwners.ViewModel!
        switch response.result {
        case .success(let owners):
            let zuppersModel = owners.map { HomeScene
                .FetchOwners
                .ViewModel
                .OwnerModel(name: $0.name,
                             photo: $0.photo,
                             type: $0.type)
            }
            viewModel = HomeScene.FetchOwners.ViewModel(result: .success(result: zuppersModel, owners: owners))
        case .failure(let err):
            viewModel = HomeScene.FetchOwners.ViewModel(result: .failure(errorMessege: err.localizedDescription))
        }
        output?.displayOwners(viewModel: viewModel)
    }
}
