//
//  HomeViewController.swift
//  MetaPod
//
//  Created by Anderson Moura de Oliveira on 15/01/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit
import Firebase

protocol HomeViewControllerInput {
    func displayZuppers(viewModel: HomeScene.FetchZuppers.ViewModel)
}

protocol HomeViewControllerOutput {
    func fetchZuppers(request: HomeScene.FetchZuppers.Request)
}

class HomeViewController: UIViewController, HomeViewControllerInput {

    @IBOutlet weak var headerView: UIView!
    @IBOutlet weak var logoZupImageView: UIImageView!
    @IBOutlet weak var collectionView: UICollectionView!
    
    var output: HomeViewControllerOutput?
    var router: HomeRouter?

    var zuppers: HomeScene.FetchZuppers.ViewModel.ZuppersModel = []

    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        HomeConfigurator.sharedInstance.configure(viewController: self)
    }

    override var preferredStatusBarStyle: UIStatusBarStyle {
        return .lightContent
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        registerCell()
        fetchZuppers()
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        setupStyle()
    }
    
    // MARK: Requests

    private func fetchZuppers() {
        let request = HomeScene.FetchZuppers.Request()
        output?.fetchZuppers(request: request)
    }
    
    // MARK: Display logic

    func displayZuppers(viewModel: HomeScene.FetchZuppers.ViewModel) {
        switch viewModel.result {
        case .success(let zuppers):
            self.zuppers = zuppers
            DispatchQueue.main.async {
                self.collectionView.reloadData()
            }
        case .failure(let errorMessege):
            print(errorMessege)
        }
    }
}

// MARK: Aux

extension HomeViewController {
    
    private func registerCell() {
        let repositoryCellNib = UINib(nibName: HomeCollectionViewCell.cellIdentifier, bundle: nil)
        collectionView.register(repositoryCellNib, forCellWithReuseIdentifier: HomeCollectionViewCell.cellIdentifier)
    }

    private func setupStyle() {
        guard let navBar = navigationController?.navigationBar else { return }
        navBar.isHidden = true
        logoZupImageView.dropShadow(color: UIColor.white.withAlphaComponent(0.3))
        collectionView.backgroundColor = .clear
        headerView.layer.cornerRadius = 20
        headerView.layer.maskedCorners = [.layerMinXMaxYCorner, .layerMaxXMaxYCorner]
        headerView.dropShadow()
        createGradientLayer()
    }
    
    func createGradientLayer() {
        let gradientLayer = CAGradientLayer()
        
        gradientLayer.frame = view.bounds
        gradientLayer.colors = [#colorLiteral(red: 0.2928162217, green: 0.3328040242, blue: 0.3703248203, alpha: 1).cgColor, #colorLiteral(red: 0.1045968458, green: 0.1450966299, blue: 0.1536100507, alpha: 1).cgColor]
        gradientLayer.startPoint = CGPoint(x: 0, y: 0)
        gradientLayer.endPoint = CGPoint(x: 1, y: 1)
        
        view.layer.insertSublayer(gradientLayer, below: collectionView.layer)
    }
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension HomeViewController: HomePresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}
