//
//  HomeInteractor.swift
//  MetaPod
//
//  Created by Anderson Moura de Oliveira on 15/01/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol HomeInteractorInput {
    func fetchZuppers(request: HomeScene.FetchZuppers.Request)
}

protocol HomeInteractorOutput {
    func presentZuppers(response: HomeScene.FetchZuppers.Response)
}

protocol HomeDataSource {
    
}

protocol HomeDataDestination {
    
}

class HomeInteractor: HomeInteractorInput, HomeDataSource, HomeDataDestination {
    
    var output: HomeInteractorOutput?
//    let provider: ZupperWorker
    let provider: OwnerWorker

    init(provider: OwnerWorker = OwnerWorker.singleton) {
        self.provider = provider
    }
    // MARK: Business logic

    func fetchZuppers(request: HomeScene.FetchZuppers.Request) {
        provider.search { (result) in
            let response = HomeScene.FetchZuppers.Response(result: result)
            self.output?.presentZuppers(response: response)
        }
    }
}
