//
//  HomeInteractor.swift
//  MetaPod
//
//  Created by Anderson Moura de Oliveira on 15/01/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol HomeInteractorInput {
    func fetchOwners(request: HomeScene.FetchOwners.Request)
    func selectOwner(request: HomeScene.SelectOwner.Request)
}

protocol HomeInteractorOutput {
    func presentOwners(response: HomeScene.FetchOwners.Response)
}

protocol HomeDataSource {
    var ownerSelected: Owner! { get }
}

protocol HomeDataDestination {
    
}

class HomeInteractor: HomeInteractorInput, HomeDataSource, HomeDataDestination {
    
    var output: HomeInteractorOutput?
    let provider: OwnerWorker
    var ownerSelected: Owner!

    init(provider: OwnerWorker = OwnerWorker.singleton) {
        self.provider = provider
    }
    // MARK: Business logic

    func fetchOwners(request: HomeScene.FetchOwners.Request) {
        provider.search { (result) in
            let response = HomeScene.FetchOwners.Response(result: result)
            self.output?.presentOwners(response: response)
        }
    }

    func selectOwner(request: HomeScene.SelectOwner.Request) {
        ownerSelected = request.ownerSelected
    }
}
