//
//  RankingModels.swift
//  MetaPod
//
//  Created by Anderson Moura de Oliveira on 16/01/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

struct RankingScene {

    struct FetchAll {
        
        struct Request {
            
        }
        
        struct Response {

            let result: InteractorResult<Zuppers>
        }
        
        struct ViewModel {

            typealias ZuppersModel = [ZupperModel]

            struct ZupperModel {
                
                let name: String
                let photo: String
            }
            
            enum PresenterResult {
                case success(result: ZuppersModel)
                case failure(errorMessege: String)
            }
            
            let result: PresenterResult
        }
    }
}
