//
//  RankingRouter.swift
//  MetaPod
//
//  Created by Anderson Moura de Oliveira on 16/01/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol RankingRouterInput {
    
}

protocol RankingRouterDataSource: class {
    
}

protocol RankingRouterDataDestination: class {
    
}

class RankingRouter: RankingRouterInput {
    
    weak var viewController: RankingViewController!
    weak private var dataSource: RankingRouterDataSource!
    weak var dataDestination: RankingRouterDataDestination!
    
    init(viewController: RankingViewController, dataSource: RankingRouterDataSource, dataDestination: RankingRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
