//
//  RankingPresenter.swift
//  MetaPod
//
//  Created by Anderson Moura de Oliveira on 16/01/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol RankingPresenterInput {
    
}

protocol RankingPresenterOutput: class {
    
}

class RankingPresenter: RankingPresenterInput {
    
    weak var output: RankingPresenterOutput?
    
    // MARK: Presentation logic
    
}
