//
//  RankingViewController.swift
//  MetaPod
//
//  Created by Anderson Moura de Oliveira on 16/01/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol RankingViewControllerInput {
    func displayRanking(viewModel: RankingScene.FetchAll.ViewModel)
}

protocol RankingViewControllerOutput {
    func fetchRanking(request: RankingScene.FetchAll.Request)
}

class RankingViewController: UIViewController, RankingViewControllerInput {

    @IBOutlet weak var collectionView: UICollectionView!
    
    var output: RankingViewControllerOutput?
    var router: RankingRouter?
    var zuppersRaking: RankingScene.FetchAll.ViewModel.ZuppersModel = []
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        RankingConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupStyle()
        registerCell()
        fetchAll()
    }

    override var preferredStatusBarStyle: UIStatusBarStyle {
        return .lightContent
    }
    
    // MARK: Requests

    private func fetchAll() {
        let request = RankingScene.FetchAll.Request()
        output?.fetchRanking(request: request)
    }
    
    // MARK: Display logic
    
    func displayRanking(viewModel: RankingScene.FetchAll.ViewModel) {
        switch viewModel.result {
        case .success(let zuppers):
            zuppersRaking = zuppers
            DispatchQueue.main.async {
                self.collectionView.reloadData()
            }
        case .failure(let errorMessege):
            print(errorMessege)
        }
    }
}

extension RankingViewController {

    private func registerCell() {
        let rankingCellNib = UINib(nibName: RankingCollectionViewCell.identifierCell, bundle: nil)
        collectionView.register(rankingCellNib, forCellWithReuseIdentifier: RankingCollectionViewCell.identifierCell)
    }
}

// MARK: Style

extension RankingViewController {

    private func setupStyle() {
        collectionView.backgroundColor = .clear
    }
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension RankingViewController: RankingPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}
