//
//  RankingInteractor.swift
//  MetaPod
//
//  Created by Anderson Moura de Oliveira on 16/01/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol RankingInteractorInput {
    func fetchRanking(request: RankingScene.FetchAll.Request)
}

protocol RankingInteractorOutput {
    func presentRanking(response: RankingScene.FetchAll.Response)
}

protocol RankingDataSource {
    
}

protocol RankingDataDestination {
    
}

class RankingInteractor: RankingInteractorInput, RankingDataSource, RankingDataDestination {
    
    var output: RankingInteractorOutput?
    let provider: ZupperWorker
    
    init(provider: ZupperWorker = ZupperWorker.singleton) {
        self.provider = provider
    }
    // MARK: Business logic
    
    func fetchRanking(request: RankingScene.FetchAll.Request) {
        provider.fetchAll { (result) in
            let response = RankingScene.FetchAll.Response(result: result)
            self.output?.presentRanking(response: response)
        }
    }
}
