//
//  MetricsDetailModels.swift
//  MetaPod
//
//  Created by Anderson Oliveira on 11/02/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

struct MetricsDetailScene {
    
}
