//
//  MetricsDetailRouter.swift
//  MetaPod
//
//  Created by Anderson Oliveira on 11/02/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol MetricsDetailRouterInput {
    
}

protocol MetricsDetailRouterDataSource: class {
    
}

protocol MetricsDetailRouterDataDestination: class {
    
}

class MetricsDetailRouter: MetricsDetailRouterInput {
    
    weak var viewController: MetricsDetailViewController!
    weak private var dataSource: MetricsDetailRouterDataSource!
    weak var dataDestination: MetricsDetailRouterDataDestination!
    
    init(viewController: MetricsDetailViewController, dataSource: MetricsDetailRouterDataSource, dataDestination: MetricsDetailRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
