//
//  HomeDetailPresenter.swift
//  MetaPod
//
//  Created by Anderson Moura de Oliveira on 20/01/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol HomeDetailPresenterInput {
    func presentOwner(response: HomeDetailScene.SelectOwner.Response)
}

protocol HomeDetailPresenterOutput: class {
    func displayOwner(viewModel: HomeDetailScene.SelectOwner.ViewModel)
}

class HomeDetailPresenter: HomeDetailPresenterInput {
    
    weak var output: HomeDetailPresenterOutput?
    
    // MARK: Presentation logic

    func presentOwner(response: HomeDetailScene.SelectOwner.Response) {
        let ownerFormatted = HomeDetailScene
            .SelectOwner
            .ViewModel
            .OwnerModel(name: response.owner.name,
                        photo: response.owner.photo,
                        type: response.owner.type)
        let viewModel = HomeDetailScene.SelectOwner.ViewModel(owner: ownerFormatted)
        output?.displayOwner(viewModel: viewModel)
    }
}
