//
//  HomeDetailRouter.swift
//  MetaPod
//
//  Created by Anderson Moura de Oliveira on 20/01/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol HomeDetailRouterInput {
    
}

protocol HomeDetailRouterDataSource: class {
    
}

protocol HomeDetailRouterDataDestination: class {
    var owner: Owner! { get set }
}

class HomeDetailRouter: HomeDetailRouterInput {
    
    weak var viewController: HomeDetailViewController!
    weak private var dataSource: HomeDetailRouterDataSource!
    weak var dataDestination: HomeDetailRouterDataDestination!
    
    init(viewController: HomeDetailViewController, dataSource: HomeDetailRouterDataSource, dataDestination: HomeDetailRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
