//
//  HomeDetailConfigurator.swift
//  MetaPod
//
//  Created by Anderson Moura de Oliveira on 20/01/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension HomeDetailInteractor: HomeDetailViewControllerOutput, HomeDetailRouterDataSource, HomeDetailRouterDataDestination {
    
}

extension HomeDetailPresenter: HomeDetailInteractorOutput {
}

class HomeDetailConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = HomeDetailConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: HomeDetailViewController) {
        
        let presenter = HomeDetailPresenter()
        presenter.output = viewController
        
        let interactor = HomeDetailInteractor()
        interactor.output = presenter
        
        let router = HomeDetailRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
