//
//  HomeDetailInteractor.swift
//  MetaPod
//
//  Created by Anderson Moura de Oliveira on 20/01/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol HomeDetailInteractorInput {
    func selectOwner(request: HomeDetailScene.SelectOwner.Request)
}

protocol HomeDetailInteractorOutput {
    func presentOwner(response: HomeDetailScene.SelectOwner.Response)
}

protocol HomeDetailDataSource {

}

protocol HomeDetailDataDestination {
    var owner: Owner! { get }
}

class HomeDetailInteractor: HomeDetailInteractorInput, HomeDetailDataSource, HomeDetailDataDestination {
    
    var output: HomeDetailInteractorOutput?
    var owner: Owner!

    // MARK: Business logic
    
    func selectOwner(request: HomeDetailScene.SelectOwner.Request) {
        let response = HomeDetailScene.SelectOwner.Response(owner: owner)
        output?.presentOwner(response: response)
    }
}
