//
//  HomeDetailViewController.swift
//  MetaPod
//
//  Created by Anderson Moura de Oliveira on 20/01/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol HomeDetailViewControllerInput {
    func displayOwner(viewModel: HomeDetailScene.SelectOwner.ViewModel)
}

protocol HomeDetailViewControllerOutput {
    func selectOwner(request: HomeDetailScene.SelectOwner.Request)
}

class HomeDetailViewController: UIViewController, HomeDetailViewControllerInput {

    @IBOutlet weak var headerView: UIView!
    @IBOutlet weak var profileView: UIView!
    @IBOutlet weak var profileImageView: UIImageView!
    @IBOutlet weak var nameLabel: UILabel!
    @IBOutlet weak var typeLabel: UILabel!
    
    var output: HomeDetailViewControllerOutput?
    var router: HomeDetailRouter?

    var owner: HomeScene.FetchOwners.ViewModel.OwnerModel!
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        HomeDetailConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setNeedsStatusBarAppearanceUpdate()
        setupStyle()
        selectOwner()
    }

    override var preferredStatusBarStyle: UIStatusBarStyle {
        return .lightContent
    }
    
    // MARK: Requests

    func selectOwner() {
        let request = HomeDetailScene.SelectOwner.Request()
        output?.selectOwner(request: request)
    }
    
    // MARK: Display logic

    func displayOwner(viewModel: HomeDetailScene.SelectOwner.ViewModel) {
        profileImageView.loadImageUsingCache(withUrlString: viewModel.owner.photo, defaultImage: #imageLiteral(resourceName: "github.png"), loadingActivityIndicatorStyle: .white)
        nameLabel.text = viewModel.owner.name
        typeLabel.text = viewModel.owner.type
    }
}

// MARK: IBActions

extension HomeDetailViewController {

    @IBAction func closeTapped(_ sender: UIButton) {
        dismiss(animated: true, completion: nil)
    }
}

extension HomeDetailViewController {

    private func setupStyle() {
        headerView.layer.cornerRadius = 20.0
        headerView.layer.maskedCorners = [.layerMinXMaxYCorner, .layerMaxXMaxYCorner]
        headerView.dropShadow()
        profileImageView.layer.cornerRadius = profileImageView.frame.height / 2.0
        profileView.dropShadow()
    }
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension HomeDetailViewController: HomeDetailPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}
