//
//  MetricsDetailInteractor.swift
//  MetaPod
//
//  Created by Anderson Oliveira on 11/02/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol MetricsDetailInteractorInput {
    
}

protocol MetricsDetailInteractorOutput {
    
}

protocol MetricsDetailDataSource {
    
}

protocol MetricsDetailDataDestination {
    
}

class MetricsDetailInteractor: MetricsDetailInteractorInput, MetricsDetailDataSource, MetricsDetailDataDestination {
    
    var output: MetricsDetailInteractorOutput?
    
    // MARK: Business logic
    

}
