//
//  MetricsSummaryPresenter.swift
//  MetaPod
//
//  Created by Anderson Moura de Oliveira on 11/02/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol MetricsSummaryPresenterInput {
    
}

protocol MetricsSummaryPresenterOutput: class {
    
}

class MetricsSummaryPresenter: MetricsSummaryPresenterInput {
    
    weak var output: MetricsSummaryPresenterOutput?
    
    // MARK: Presentation logic
    
}
