//
//  MetricsSummaryInteractor.swift
//  MetaPod
//
//  Created by Anderson Moura de Oliveira on 11/02/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol MetricsSummaryInteractorInput {
    
}

protocol MetricsSummaryInteractorOutput {
    
}

protocol MetricsSummaryDataSource {
    
}

protocol MetricsSummaryDataDestination {
    
}

class MetricsSummaryInteractor: MetricsSummaryInteractorInput, MetricsSummaryDataSource, MetricsSummaryDataDestination {
    
    var output: MetricsSummaryInteractorOutput?
    
    // MARK: Business logic
    

}
