//
//  MetricsSummaryConfigurator.swift
//  MetaPod
//
//  Created by Anderson Moura de Oliveira on 11/02/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension MetricsSummaryInteractor: MetricsSummaryViewControllerOutput, MetricsSummaryRouterDataSource, MetricsSummaryRouterDataDestination {
}

extension MetricsSummaryPresenter: MetricsSummaryInteractorOutput {
}

class MetricsSummaryConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = MetricsSummaryConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: MetricsSummaryViewController) {
        
        let presenter = MetricsSummaryPresenter()
        presenter.output = viewController
        
        let interactor = MetricsSummaryInteractor()
        interactor.output = presenter
        
        let router = MetricsSummaryRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
