//
//  MetricsSummaryRouter.swift
//  MetaPod
//
//  Created by Anderson Moura de Oliveira on 11/02/19.
//  Copyright (c) 2019 Zup. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol MetricsSummaryRouterInput {
    
}

protocol MetricsSummaryRouterDataSource: class {
    
}

protocol MetricsSummaryRouterDataDestination: class {
    
}

class MetricsSummaryRouter: MetricsSummaryRouterInput {
    
    weak var viewController: MetricsSummaryViewController!
    weak private var dataSource: MetricsSummaryRouterDataSource!
    weak var dataDestination: MetricsSummaryRouterDataDestination!
    
    init(viewController: MetricsSummaryViewController, dataSource: MetricsSummaryRouterDataSource, dataDestination: MetricsSummaryRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
